#!/usr/bin/env python3
"""Bake a piece of artwork into a C alpha-coverage mask header — the same
trick as gen_dvdlogo.py, but from a local file, for the disc-loading animation.

The player ships no image decoder, so artwork is compiled in as a byte array
of 8-bit coverage and blitted tinted: out = lerp(bg, tint, alpha[y*W + x]).

    python3 gen_asset.py <in.png> <name> [target_width]

Writes src/ui/<name>_data.h with PIDVD_<NAME>_W / _H and pidvd_<name>_a[W*H].

Coverage source: a transparent-background PNG uses its alpha channel; a fully
opaque image (e.g. black line-art on white) falls back to inverted luminance,
so either export style works.
"""
import sys
from pathlib import Path
from PIL import Image


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: gen_asset.py <in.png> <name> [target_width]")
    src = Path(sys.argv[1])
    name = sys.argv[2].lower()
    tw = int(sys.argv[3]) if len(sys.argv) > 3 else 320

    im = Image.open(src).convert("RGBA")
    alpha = im.split()[-1]
    if alpha.getextrema()[0] == 255:          # no transparency: use darkness
        cov = im.convert("L").point(lambda v: 255 - v)
    else:
        cov = alpha

    bbox = cov.getbbox()                       # tight crop to the drawn shape
    if bbox:
        cov = cov.crop(bbox)
    w0, h0 = cov.size
    th = max(1, round(tw * h0 / w0))
    if th % 2:                                 # even height -> clean 2:1 decimation
        th += 1
    cov = cov.resize((tw, th), Image.LANCZOS)
    data = cov.tobytes()
    assert len(data) == tw * th

    NAME = name.upper()
    out = Path(__file__).resolve().parent.parent / "src" / "ui" / f"{name}_data.h"
    lines = [f"/* {name} art, 8-bit alpha coverage, row-major. GENERATED by",
             f" * tools/gen_asset.py from {src.name}. Do not hand-edit. Blit",
             " * tinted: out = lerp(bg, tint, alpha[y*W + x]). */",
             f"#ifndef PIDVD_UI_{NAME}_DATA_H",
             f"#define PIDVD_UI_{NAME}_DATA_H",
             "",
             "#include <stdint.h>",
             "",
             f"#define PIDVD_{NAME}_W {tw}",
             f"#define PIDVD_{NAME}_H {th}",
             "",
             f"static const uint8_t pidvd_{name}_a[{tw} * {th}] = {{"]
    for i in range(0, len(data), 20):
        chunk = data[i:i + 20]
        lines.append("    " + "".join(f"{b:3d}," for b in chunk))
    lines += ["};", "", "#endif", ""]
    out.write_text("\n".join(lines))
    print(f"wrote {out}  ({tw}x{th}, {len(data)} bytes coverage)")


if __name__ == "__main__":
    main()
