#!/usr/bin/env python3
"""Bake the DVD-Video logo into a C alpha-coverage mask header.

The player ships no image decoder, so the bouncing-logo screensaver gets its
artwork the same way it gets its font: as a static byte array compiled in.

Source: Wikimedia Commons "DVD-Video Logo.svg", a public-domain text/logo
(simple geometric shapes — PD-textlogo). We pull a rasterised PNG of it via
MediaWiki's Special:FilePath?width= (no local SVG renderer needed), crop to
the opaque bounding box, downscale, and emit the alpha channel as 8-bit
coverage. Blit it tinted: out = lerp(bg, tint, alpha).

    python3 gen_dvdlogo.py [target_width]    # default 184; writes the header

Regenerate only when you want to change the embedded resolution.
"""
import sys, urllib.request
from pathlib import Path
from PIL import Image

SRC = ("https://commons.wikimedia.org/wiki/Special:FilePath/"
       "DVD-Video_Logo.svg?width=960")
OUT = Path(__file__).resolve().parent.parent / "src" / "ui" / "dvdlogo_data.h"
TARGET_W = int(sys.argv[1]) if len(sys.argv) > 1 else 184

def main():
    req = urllib.request.Request(SRC, headers={"User-Agent": "pidvd-gen/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        import io
        im = Image.open(io.BytesIO(r.read())).convert("LA")
    alpha = im.split()[-1]
    bbox = alpha.getbbox()                 # tight crop to the opaque shape
    alpha = alpha.crop(bbox)
    w0, h0 = alpha.size
    tw = TARGET_W
    th = max(1, round(tw * h0 / w0))
    if th % 2:                              # even height: clean 2:1 decimation
        th += 1
    alpha = alpha.resize((tw, th), Image.LANCZOS)
    data = alpha.tobytes()                  # row-major, 1 byte/px
    assert len(data) == tw * th

    lines = ["/* DVD-Video logo, 8-bit alpha coverage, row-major. GENERATED by",
             " * tools/gen_dvdlogo.py from the public-domain Wikimedia Commons",
             " * \"DVD-Video Logo.svg\" (PD-textlogo). Do not hand-edit. Blit",
             " * tinted: out = lerp(bg, tint, alpha[y*W + x]). */",
             "#ifndef PIDVD_UI_DVDLOGO_DATA_H",
             "#define PIDVD_UI_DVDLOGO_DATA_H",
             "",
             "#include <stdint.h>",
             "",
             f"#define PIDVD_DVDLOGO_W {tw}",
             f"#define PIDVD_DVDLOGO_H {th}",
             "",
             f"static const uint8_t pidvd_dvdlogo_a[{tw} * {th}] = {{"]
    for i in range(0, len(data), 20):
        chunk = data[i:i + 20]
        lines.append("    " + "".join(f"{b:3d}," for b in chunk))
    lines += ["};", "", "#endif", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}  ({tw}x{th}, {len(data)} bytes coverage)")

if __name__ == "__main__":
    main()
